char1 = ord('B')
char2 = ord('C')
char3 = ord('D')
char4 = ord('b')
char5 = ord('c')
char6 = ord('d')
char7 = ord('1')
char8 = ord('0')
char9 = ord('2')
char11 = ord('$')
char12 = ord('*')
char13 = ord('+')
print(char1,"\n",char2,"\n",char3,"\n",char4,"\n",char5,"\n",char6,"\n",char7,"\n",char8,"\n",char9,"\n",char11,"\n",char12,"\n",char13)